### ISSUE TITLE
Releases/Builds?

### ISSUE THREAD

**Issue by no-identd** [AdamRakaska/MixedRadixCalculator#1]
Any releases/builds of this available anywhere? Your website seems dead.

**Comment by AdamRakaska** [comment]
I checked in a compiled .exe to the \bin folder on the master branch: [https://github.com/AdamRakaska/MixedRadixCalculator/blob/master/RadixCalculator/bin/Debug/RadixCalculator.exe](https://github.com/AdamRakaska/MixedRadixCalculator/blob/master/RadixCalculator/bin/Debug/RadixCalculator.exe)

**Comment by AdamRakaska** [comment]
Also my new website domain is [https://csharpcodewhisperer.blogspot.com](https://csharpcodewhisperer.blogspot.com)

**Comment by no-identd** [comment]
Thanks!
