### ISSUE TITLE
Non-integer base support or at least error on them?

### ISSUE THREAD

**Issue by no-identd** [AdamRakaska/MixedRadixCalculator#5]
I tried to add 1.618034 (the closest IEEE double float approximation of the golden ratio) as a base. Unfortunately, it didn't work - **and** it didn't even give an error message.

**Comment by AdamRakaska** [comment]
Yeah, this is not supported. Ill think about if there is an easy / sane way to support such a feature. In the interim, I added error handling and input validation so it no longer fails silently.
